name: pics
favicon: null
layout_spectrum: 0
typography_spectrum: 0.86514
title: 'pictures, mostly from traveling across the world'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
