name: pics
favicon: null
layout_spectrum: 0.0635356183629483
typography_spectrum: 0.9854823390487581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5774072795175016
  lightness: 0.9693582344334573
  saturation: 0.0038629521150141954
  rhythmicContrast: 0.8127190165687352
purpose: []
